name: Test and Create Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug    
          tools: php-cs-fixer, phpunit
      - name: Test with phpunit
        run: mkdir coverage && vendor/bin/phpunit --coverage-text coverage/coverage.txt